label: Enrollment

authorized_signer:
    rule1:
        # Full DN
        subject: CN=.+:scepclient,.*
    rule2:
        # Full DN
        subject: CN=.+:pkiclient,.*

renewal_period: 000060

# You must set at least one of both options or remove the is_policy_loaded
# condition in the workflow definition
policy:
    allow_man_authen: 0
    allow_man_approv: 0
    max_active_certs: 0
    auto_revoke_existing_certs: 1
    approval_points: 1
    export_certificate: chain

profile:
    cert_profile: tls_server
    cert_subject_style: enroll


eligible:
    initial:
        value: 1

    renewal:
        value: 1

    onbehalf:
       value: 1
